name: AutoUpdateGeyser
main: spigot.AutoUpdateGeyser
version: '7.0.0'
description: Plugin to automate updating of both Geyser and Floodgate
author: 'NewAmazingPVP'
api-version: 1.13
folia-supported: true
commands:
  updategeyser:
    description: Force update checker for geyser and floodgate!
    usage: /updategeyser
    permission: autoupdategeyser.admin
    default: op
