name: AutoUpdateGeyser
main: spigot.AutoUpdateGeyser
version: '6.0'
# hackfix (definitely will not work as intended)
folia-supported: true
description: Plugin to automate updating of both Geyser and Floodgate
author: 'NewAmazingPVP'
commands:
  updategeyser:
    description: Force update checker for geyser and floodgate!
    usage: /updategeyser
    permission: autoupdategeyser.admin
    default: op